// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID         string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Name       string
	Password   string
	AvatarPath sql.NullString
}
