// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (id, created_at, updated_at, email, name, password)
VALUES
  (?, ?, ?, ?, ?, ?)
RETURNING
  id, created_at, updated_at, email, name, password, profile_picture_url
`

type CreateUserParams struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Name      string
	Password  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.Name,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE
  id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, created_at, updated_at, email, name, password, profile_picture_url
FROM
  users
WHERE
  email = ?
LIMIT
  1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
  id, created_at, updated_at, email, name, password, profile_picture_url
FROM
  users
WHERE
  id = ?
LIMIT
  1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET
  password = ?,
  updated_at = ?
WHERE
  id = ?
RETURNING
  id, created_at, updated_at, email, name, password, profile_picture_url
`

type UpdatePasswordParams struct {
	Password  string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePassword, arg.Password, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const updatePersonalInfo = `-- name: UpdatePersonalInfo :one
UPDATE users
SET
  name = ?,
  email = ?,
  updated_at = ?
WHERE
  id = ?
RETURNING
  id, created_at, updated_at, email, name, password, profile_picture_url
`

type UpdatePersonalInfoParams struct {
	Name      string
	Email     string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) UpdatePersonalInfo(ctx context.Context, arg UpdatePersonalInfoParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updatePersonalInfo,
		arg.Name,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}

const updateProfilePicture = `-- name: UpdateProfilePicture :one
UPDATE users
SET
  profile_picture_url = ?,
  updated_at = ?
WHERE
  id = ?
RETURNING
  id, created_at, updated_at, email, name, password, profile_picture_url
`

type UpdateProfilePictureParams struct {
	ProfilePictureUrl sql.NullString
	UpdatedAt         time.Time
	ID                string
}

func (q *Queries) UpdateProfilePicture(ctx context.Context, arg UpdateProfilePictureParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateProfilePicture, arg.ProfilePictureUrl, arg.UpdatedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.ProfilePictureUrl,
	)
	return i, err
}
